### ISSUE TITLE
Arduino Support

### ISSUE THREAD

**Issue by NoNamedCat** [IOsetting/py32f0-template#26]
Hello, thank you for this project once again.
I want to add Arduino support for the PY32F002.
As IOsetting mentioned earlier, there are some projects that do this for another chip called AIR001.
I've collected some test sketches and can confirm that if I upload the hexadecimal to the PY32F002, it works perfectly.
So, I'm thinking of cloning the repository and adapting the source code for this MCU.
I have some questions about how to do this.
Is it correct to take the source code from the repository and adapt it for this MCU?
Would any of you be interested in doing this?
Is it worth doing this?
Some of you have mentioned that the resources of this MCU might not be sufficient for the Arduino environment.
Based on the results and libraries ported by the other project, do you believe this to be the case?
Thank you and warm regards!

**Comment by NoNamedCat** [comment]
This is the site for the project:

https://wiki.luatos.com/chips/air001/index.html

**Comment by IOsetting** [comment]
I seldom use Arduino so I don't have an idea, maybe you can fork it and make further changes to make it support PY32 types?
BTW I don't like their ISP tool because it need .NET runtime, I don't use .NET in Ubuntu. If I got time I would write one in C.

**Comment by NoNamedCat** [comment]
I'm in a rabbit hole....

'''c++
#include <stdio.h>
#include <stdlib.h>
#include <hidapi/hidapi.h>
#include <unistd.h>
#include <string.h>

#define REPORT_SIZE 64
#define RETRY_DELAY_SECONDS 5

// Function to send data to the CMSIS-DAP adapter
void send_data(hid_device *device, const unsigned char *data, size_t size) {
    int bytes_sent = hid_write(device, data, size);
    if (bytes_sent < 0) {
        printf("Error sending data\n");
        exit(-1);
    }
}

void print_progress_bar(float progress) {
    int bar_width = 50;
    int pos = bar_width * progress;
    printf("[");
    for (int i = 0; i < bar_width; ++i) {
        if (i < pos) printf("=");
        else printf(" ");
    }
    printf("] %.2f%%\r", progress * 100);
    fflush(stdout);
}

int main(int argc, char *argv[]) {
    if (argc != 2) {
        printf("Usage: %s <file_path>\n", argv[0]);
        return -1;
    }

    const char *file_path = argv[1];
    const char *id_list_file_path = "./ids.txt"; // Corrected path

    hid_device *device;
    unsigned char buf[REPORT_SIZE];

    // Initialize HIDAPI
    if (hid_init() != 0) {
        printf("Failed to initialize HIDAPI\n");
        return -1;
    }
    printf("HIDAPI initialized\n");

    // Open the ID list file for reading
    FILE *id_list_file = fopen(id_list_file_path, "r");
    if (!id_list_file) {
        printf("Failed to open ID list file %s\n", id_list_file_path);
        hid_exit();
        return -1;
    }
    printf("ID list file opened: %s\n", id_list_file_path);

    // Read USB vendor and product IDs from the list file
    unsigned int vendor_id, product_id;
    while (fscanf(id_list_file, " %x %x", &vendor_id, &product_id) == 2) {
        bool device_found = false;
        int retry_count = 0;

        while (!device_found && retry_count < RETRY_DELAY_SECONDS) {
            // Open the CMSIS-DAP adapter with the specified IDs
            device = hid_open(vendor_id, product_id, NULL);
            if (device) {
                printf("Device with Vendor ID: %04x, Product ID: %04x found and opened\n", vendor_id, product_id);
                device_found = true;
            } else {
                printf("Device with Vendor ID: %04x, Product ID: %04x not found or couldn't be opened. Retrying...\n", vendor_id, product_id);
                retry_count++;
                sleep(1); // Wait for 1 second before retrying
            }
        }

        if (!device_found) {
            printf("Device with Vendor ID: %04x, Product ID: %04x not found after waiting.\n", vendor_id, product_id);
            continue;
        }

        // Rest of the flashing logic (same as before)
        printf("Flashing file: %s\n", file_path);

        // Open the file for reading
        FILE *file = fopen(file_path, "rb");
        if (!file) {
            printf("Failed to open file %s\n", file_path);
            hid_close(device);
            fclose(id_list_file);
            hid_exit();
            return -1;
        }

        // Get the file size
        fseek(file, 0, SEEK_END);
        size_t file_size = ftell(file);
        rewind(file);

        // Send the erase command (replace with actual command)
        buf[0] = 0x02; // Replace with the erase command
        send_data(device, buf, 1);
        printf("Erase command sent\n");

        // Divide the file data into chunks and send them to the microcontroller
        size_t chunk_size = REPORT_SIZE - 1; // One byte is reserved for command
        size_t offset = 0;

        while (offset < file_size) {
            // Prepare the command (index 0) and data for this chunk
            buf[0] = 0x01; // Replace with the flash command
            size_t chunk_actual_size = file_size - offset;
            if (chunk_actual_size > chunk_size) {
                chunk_actual_size = chunk_size;
            }
            fread(&buf[1], 1, chunk_actual_size, file);

            // Send the chunk to the microcontroller
            send_data(device, buf, chunk_actual_size + 1); // +1 for the command byte

            offset += chunk_actual_size;
            print_progress_bar((float)offset / file_size);
        }

        // Close the file
        fclose(file);
        printf("\nFile flashed\n");

        // Verify the flashed data
        bool verification_failed = false;
        FILE *verification_file = fopen(file_path, "rb");
        offset = 0;

        while (offset < file_size) {
            size_t chunk_actual_size = file_size - offset;
            if (chunk_actual_size > chunk_size) {
                chunk_actual_size = chunk_size;
            }

            unsigned char verification_buf[chunk_actual_size];
            fread(verification_buf, 1, chunk_actual_size, verification_file);

            // Read data back from microcontroller's flash memory
            unsigned char read_buf[chunk_actual_size + 1];
            read_buf[0] = 0x03; // Replace with the read command
            send_data(device, read_buf, 1);

            // Receive the read data from the microcontroller
            int bytes_received = hid_read(device, read_buf, sizeof(read_buf));

            if (bytes_received < 0) {
                printf("Error receiving data\n");
                verification_failed = true;
                break;
            }

            // Compare the received data with the original data
            if (memcmp(read_buf + 1, verification_buf, chunk_actual_size) != 0) {
                printf("Verification failed for chunk at offset %zu\n", offset);
                verification_failed = true;
                break;
            }

            offset += chunk_actual_size;
            print_progress_bar((float)offset / file_size);
        }

        fclose(verification_file);

        if (!verification_failed) {
            printf("Verification succeeded: Flashed data matches original file\n");
        } else {
            printf("Verification failed: Flashed data does not match original file\n");
        }

        // Reset the microcontroller
        buf[0] = 0x00; // Replace with the reset command
        send_data(device, buf, 1);
        printf("Microcontroller reset\n");

        // Close the device
        hid_close(device);
        printf("Device closed\n");
    }

    // Close the ID list file and cleanup HIDAPI (same as before)
    fclose(id_list_file);
    printf("ID list file closed\n");
    hid_exit();
    printf("HIDAPI cleaned up\n");

    return 0;
}
'''

**Comment by NoNamedCat** [comment]
I'm in a rabbit hole right now...

I'm trying to make a program that interface with the USB-DAP adapter...

```c++

#include <stdio.h>
#include <stdlib.h>
#include <hidapi/hidapi.h>
#include <unistd.h>
#include <string.h>

#define REPORT_SIZE 64
#define RETRY_DELAY_SECONDS 5

// Function to send data to the CMSIS-DAP adapter
void send_data(hid_device *device, const unsigned char *data, size_t size) {
    int bytes_sent = hid_write(device, data, size);
    if (bytes_sent < 0) {
        printf("Error sending data\n");
        exit(-1);
    }
}

void print_progress_bar(float progress) {
    int bar_width = 50;
    int pos = bar_width * progress;
    printf("[");
    for (int i = 0; i < bar_width; ++i) {
        if (i < pos) printf("=");
        else printf(" ");
    }
    printf("] %.2f%%\r", progress * 100);
    fflush(stdout);
}

int main(int argc, char *argv[]) {
    if (argc != 2) {
        printf("Usage: %s <file_path>\n", argv[0]);
        return -1;
    }

    const char *file_path = argv[1];
    const char *id_list_file_path = "./ids.txt"; // Corrected path

    hid_device *device;
    unsigned char buf[REPORT_SIZE];

    // Initialize HIDAPI
    if (hid_init() != 0) {
        printf("Failed to initialize HIDAPI\n");
        return -1;
    }
    printf("HIDAPI initialized\n");

    // Open the ID list file for reading
    FILE *id_list_file = fopen(id_list_file_path, "r");
    if (!id_list_file) {
        printf("Failed to open ID list file %s\n", id_list_file_path);
        hid_exit();
        return -1;
    }
    printf("ID list file opened: %s\n", id_list_file_path);

    // Read USB vendor and product IDs from the list file
    unsigned int vendor_id, product_id;
    while (fscanf(id_list_file, " %x %x", &vendor_id, &product_id) == 2) {
        bool device_found = false;
        int retry_count = 0;

        while (!device_found && retry_count < RETRY_DELAY_SECONDS) {
            // Open the CMSIS-DAP adapter with the specified IDs
            device = hid_open(vendor_id, product_id, NULL);
            if (device) {
                printf("Device with Vendor ID: %04x, Product ID: %04x found and opened\n", vendor_id, product_id);
                device_found = true;
            } else {
                printf("Device with Vendor ID: %04x, Product ID: %04x not found or couldn't be opened. Retrying...\n", vendor_id, product_id);
                retry_count++;
                sleep(1); // Wait for 1 second before retrying
            }
        }

        if (!device_found) {
            printf("Device with Vendor ID: %04x, Product ID: %04x not found after waiting.\n", vendor_id, product_id);
            continue;
        }

        // Rest of the flashing logic (same as before)
        printf("Flashing file: %s\n", file_path);

        // Open the file for reading
        FILE *file = fopen(file_path, "rb");
        if (!file) {
            printf("Failed to open file %s\n", file_path);
            hid_close(device);
            fclose(id_list_file);
            hid_exit();
            return -1;
        }

        // Get the file size
        fseek(file, 0, SEEK_END);
        size_t file_size = ftell(file);
        rewind(file);

        // Send the erase command (replace with actual command)
        buf[0] = 0x02; // Replace with the erase command
        send_data(device, buf, 1);
        printf("Erase command sent\n");

        // Divide the file data into chunks and send them to the microcontroller
        size_t chunk_size = REPORT_SIZE - 1; // One byte is reserved for command
        size_t offset = 0;

        while (offset < file_size) {
            // Prepare the command (index 0) and data for this chunk
            buf[0] = 0x01; // Replace with the flash command
            size_t chunk_actual_size = file_size - offset;
            if (chunk_actual_size > chunk_size) {
                chunk_actual_size = chunk_size;
            }
            fread(&buf[1], 1, chunk_actual_size, file);

            // Send the chunk to the microcontroller
            send_data(device, buf, chunk_actual_size + 1); // +1 for the command byte

            offset += chunk_actual_size;
            print_progress_bar((float)offset / file_size);
        }

        // Close the file
        fclose(file);
        printf("\nFile flashed\n");

        // Verify the flashed data
        bool verification_failed = false;
        FILE *verification_file = fopen(file_path, "rb");
        offset = 0;

        while (offset < file_size) {
            size_t chunk_actual_size = file_size - offset;
            if (chunk_actual_size > chunk_size) {
                chunk_actual_size = chunk_size;
            }

            unsigned char verification_buf[chunk_actual_size];
            fread(verification_buf, 1, chunk_actual_size, verification_file);

            // Read data back from microcontroller's flash memory
            unsigned char read_buf[chunk_actual_size + 1];
            read_buf[0] = 0x03; // Replace with the read command
            send_data(device, read_buf, 1);

            // Receive the read data from the microcontroller
            int bytes_received = hid_read(device, read_buf, sizeof(read_buf));

            if (bytes_received < 0) {
                printf("Error receiving data\n");
                verification_failed = true;
                break;
            }

            // Compare the received data with the original data
            if (memcmp(read_buf + 1, verification_buf, chunk_actual_size) != 0) {
                printf("Verification failed for chunk at offset %zu\n", offset);
                verification_failed = true;
                break;
            }

            offset += chunk_actual_size;
            print_progress_bar((float)offset / file_size);
        }

        fclose(verification_file);

        if (!verification_failed) {
            printf("Verification succeeded: Flashed data matches original file\n");
        } else {
            printf("Verification failed: Flashed data does not match original file\n");
        }

        // Reset the microcontroller
        buf[0] = 0x00; // Replace with the reset command
        send_data(device, buf, 1);
        printf("Microcontroller reset\n");

        // Close the device
        hid_close(device);
        printf("Device closed\n");
    }

    // Close the ID list file and cleanup HIDAPI (same as before)
    fclose(id_list_file);
    printf("ID list file closed\n");
    hid_exit();
    printf("HIDAPI cleaned up\n");

    return 0;
}
```

**Comment by NoNamedCat** [comment]
I don't know much about USB HID protocol and the DAP protocol...

The binary file needs a file called "ids.txt" on the same folder of the compiled file.

You use the program like this:
./flasher ./fileToFlash.bin

**Comment by NoNamedCat** [comment]
This is the makefile:

CC = g++
CFLAGS = -std=c++11 -Wall
LIBS = -lhidapi-libusb

TARGET = flasher

all: $(TARGET)

$(TARGET): flasher.cpp
	$(CC) $(CFLAGS) -o $(TARGET) flasher.cpp $(LIBS)

clean:
	rm -f $(TARGET)

**Comment by NoNamedCat** [comment]
The program is not able to flash the microcontroller, test the connection with it, or test if the microcontroller have the correct flash information.

**Comment by NoNamedCat** [comment]
Im using the raw values of the file: 
https://github.com/IOsetting/py32f0-template/blob/main/Misc/SVD/py32f002axx.svd
Am I missing something?

**Comment by IOsetting** [comment]
@NoNamedCat I don't know what is going on, I didn't see any new replies in this thread, but I found a lot new replies in my mailbox. Regarding the USB-DAP adapter problem, I don't know much about USB HID either, maybe you can find help in [DAPLink discussions](https://github.com/ARMmbed/DAPLink/discussions)

**Comment by NoNamedCat** [comment]
Tks IOsetting. I'm trying to make a standalone program to interface with a CMIS-DAP adapter to integrate this into the Arduino IDE. I'm reading about HID, DAP protocol, and I'm trying to communicate using directly with the protocol. For now I'm using WireShark on Linux to try to reverse engineer the steps needed to flash the program on the py32f002.
Tks a lot and sorry for the spam on your email.

**Comment by NoNamedCat** [comment]
https://www.keil.com/pack/doc/CMSIS_Dev/General/html/index.html

Here are some resources. I posted here to future reference.

**Comment by NoNamedCat** [comment]
https://github.com/py32duino/Arduino-PY32

Arduino for the PY32F series is real now :)

**Comment by IOsetting** [comment]
That's great news, the Arduino support will definitely attract more users.

**Comment by NoNamedCat** [comment]
Totally agree. That makes my dreams come true. I really want the cheapest possible arduino compatible board.
Here... I give you another design. It has a CH340X for automatic reset and boot mode entering and flasing.

https://github.com/wagiminator/MCU-Flash-Tools/issues/2

The same with the older design. You can use the design as you wish. You can use it in this web page. You can sell it. You can do what you want, You don't need to credit me for that.

The board should be compatible with the puysisp tool that wagiminator created.

**Comment by NoNamedCat** [comment]
Should i close this issue?

**Comment by IOsetting** [comment]
I don't mind if it is open, but if you like, yes, of course you can close it.
