### ISSUE TITLE
get SWO to work

### ISSUE THREAD

**Issue by danyhm** [IOsetting/py32f0-template#28]
Hello,

have you been able to get SWO to work with Keil?
if yes please provide the configuration

**Comment by IOsetting** [comment]
PY32F0x has no SWO but only SWD support. 

If you mean SWD, you need to import the pack file in Keil to make it work. The pack file exists in the [SDK](https://www.puyasemi.com/uploadfiles/2023/PY32F030-PY32F003-PY32F002A-230410.rar), which can be downloaded from their [product page](https://www.puyasemi.com/cpzx3/info_267_aid_242_kid_235.html)

**Comment by danyhm** [comment]
no, I meant SWO (serial wire output). thanks for the clarification

**Comment by prosper00** [comment]
the cortex m0 core doesn't support SWO.
