### ISSUE TITLE
PY32F002B-PY32F040-PY32F072-PY32F403 PDF Files

### ISSUE THREAD

**Issue by NoNamedCat** [IOsetting/py32f0-template#32]
Here are some PDF's that you can add to the repo.
I tried to make the upload to the Docs folder but the uploads are not available. 

[Py32F002B.pdf](https://github.com/IOsetting/py32f0-template/files/13112830/Py32F002B.pdf)
[PY32F040.pdf](https://github.com/IOsetting/py32f0-template/files/13112831/PY32F040.pdf)
[Py32F072.pdf](https://github.com/IOsetting/py32f0-template/files/13112832/Py32F072.pdf)
[PY32F403.pdf](https://github.com/IOsetting/py32f0-template/files/13112833/PY32F403.pdf)

**Comment by IOsetting** [comment]
Thank you! I have been using [WIKI](https://github.com/IOsetting/py32f0-template/wiki) to organize these documents. 
The Docs folder will be removed in the future to reduce the repository size.

**Comment by NoNamedCat** [comment]
Can I close this issue?

**Comment by IOsetting** [comment]
Yes, of course.
