### ISSUE TITLE
Current Consumption in Deep Sleep LSI

### ISSUE THREAD

**Issue by garudaonekh** [IOsetting/py32f0-template#42]
In this example:
https://github.com/IOsetting/py32f0-template/blob/main/Examples/PY32F002B/LL/LPTIM/LPTIM_LSI_DeepStop_WakeUp/main.c
```

/**
  ******************************************************************************
  * PY32F002B Deep Stop Wake Up By LPTIM(LSI)
  * 
  * Connections
  *  PB5      --->    - LED +   ---> 3.3V
  *  VCC      ---> 3.3V
  *  GND      ---> GND 
  *  
  * - MCU enters deep stop mode after 3 seconds,
  * - LED blinks every 5 seconds (In low voltage LSI becomes slower and slower, the 
  *   interval will be longer than expected)
  * - Current consumption is around 0.6uA in deep stop mode
  */

```

Its description said it consumes **around 0.6uA in deep stop mode.**

Is this figure real? As per its datasheet, it should be around 5ua or above.

I don't have Py32F002B to test, I have only F002A.

**Comment by IOsetting** [comment]
002B is a different series, low power but less on-chip resources.

It's real but not officially guaranteed. In 002B's datasheet it only lists the stop mode. Deep stop mode is a feature of PY32L020, but I doubt they are the same chip.

**Comment by IOsetting** [comment]
All datasheets can be found at [WIKI](https://github.com/IOsetting/py32f0-template/wiki) page

**Comment by garudaonekh** [comment]
![Screenshot_2024-05-03-19-53-26-38_e2d5b3f32b79de1d45acd1fad96fbb0f](https://github.com/IOsetting/py32f0-template/assets/2074857/77102a16-7d8d-4788-b218-330118485b8b)
Glad to know that PY32f002B is much more power efficient than others
