### ISSUE TITLE
C++ Support

### ISSUE THREAD

**Issue by garudaonekh** [IOsetting/py32f0-template#44]
Hi,
I am from Arduino. I can get some code here to work. Somehow, I am not able to get CPP library to work here.

Any suggestion on how to get CPP to work here?

Thanks;

**Comment by IOsetting** [comment]
Adding `extern "C" { }` around C function declarations? e.g. [AIR32F10xLib](https://github.com/IOsetting/air32f103-template/tree/master/Libraries/AIR32F10xLib)

**Comment by garudaonekh** [comment]
The issue is the compiler does not recognize C++ and class.

**Comment by garudaonekh** [comment]
I think to make C++ works, I need to change to **arm-none-eabi-c++** in the rules file. Somehow, I try to change it, but some parameters are interlinked and can't run properly

**Comment by garudaonekh** [comment]
Thanks for your update for CPP support. Your blinkCPP worked.
But when I try to wrap a CPP class, i got error: `**undefined reference to `operator new(unsigned int)'**`

[Archive.zip](https://github.com/IOsetting/py32f0-template/files/15442150/Archive.zip)
I attach the whole code for the Rectangle Class

**Comment by IOsetting** [comment]
new and delete operators are not included in gcc-arm-none-eabi, use malloc and free instead.
